<a href="https://colab.research.google.com/github/ahmedbasemdev/PyTorch-Tutorial/blob/main/01_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [6]:
# create an empty tensor with n size
x = torch.empty(3)
print(x)

tensor([2.3579e-35, 0.0000e+00, 1.5975e-43])


In [7]:
x = torch.empty(2,3)
print(x)

tensor([[2.3579e-35, 0.0000e+00, 1.5975e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


it could be 3D or even more

In [8]:
# Create a tensor with random values and 2 by 2 Dimension
x= torch.rand(2,2)
print(x)

tensor([[0.1951, 0.0528],
        [0.4139, 0.3106]])


In [10]:
# Create a tensor with zeros values and 2 by 2 Dimension
x= torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [12]:
# Create a tensor with ones values and 2 by 2 Dimension
x= torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [17]:
## set the type of tensor's data
x= torch.ones(2,2,dtype=torch.float16)
## get the size of the tensor
print(x.size())

torch.Size([2, 2])


In [18]:
# we can also create a tensor from list
x = torch.tensor([100,.15,20])
print(x)

tensor([100.0000,   0.1500,  20.0000])


In [20]:
x= torch.rand(2,2)
y = torch.rand(2,2)
print(x,"\n")
print(y,'\n')
# we can use torch.add() , it will do the same thing
z = x + y
print(z)

tensor([[0.3461, 0.3150],
        [0.2792, 0.9776]]) 

tensor([[0.4959, 0.6383],
        [0.2167, 0.5233]]) 

tensor([[0.8420, 0.9533],
        [0.4958, 1.5009]])


in pyTorch every function with _ will do an inplace operation

In [21]:
# we can do inplace_addition , this will modify y and add all of the elements of x to y
y.add_(x)
print(y)

tensor([[0.8420, 0.9533],
        [0.4958, 1.5009]])
