<a href="https://colab.research.google.com/github/ahmedbasemdev/PyTorch-Tutorial/blob/main/01_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# create an empty tensor with n size
x = torch.empty(3)
print(x)

tensor([4.9718e-35, 0.0000e+00, 3.3631e-44])


In [3]:
x = torch.empty(2,3)
print(x)

tensor([[4.9720e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


it could be 3D or even more

In [4]:
# Create a tensor with random values and 2 by 2 Dimension
x= torch.rand(2,2)
print(x)

tensor([[0.3084, 0.0605],
        [0.3961, 0.4514]])


In [5]:
# Create a tensor with zeros values and 2 by 2 Dimension
x= torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
# Create a tensor with ones values and 2 by 2 Dimension
x= torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
## set the type of tensor's data
x= torch.ones(2,2,dtype=torch.float16)
## get the size of the tensor
print(x.size())

torch.Size([2, 2])


In [8]:
# we can also create a tensor from list
x = torch.tensor([100,.15,20])
print(x)

tensor([100.0000,   0.1500,  20.0000])


In [9]:
x= torch.rand(2,2)
y = torch.rand(2,2)
print(x,"\n")
print(y,'\n')
# we can use torch.add() , it will do the same thing
z = x + y
print(z)

tensor([[0.5101, 0.2862],
        [0.6310, 0.2524]]) 

tensor([[0.0525, 0.2426],
        [0.5583, 0.0065]]) 

tensor([[0.5627, 0.5287],
        [1.1893, 0.2588]])


in pyTorch every function with _ will do an inplace operation

In [10]:
# we can do inplace_addition , this will modify y and add all of the elements of x to y
y.add_(x)
print(y)

tensor([[0.5627, 0.5287],
        [1.1893, 0.2588]])


In [11]:
z = x - y
# or 
z = torch.sub(x,y) 

In [12]:
z = x * y
# or 
z = torch.mul(x,y)

In [13]:
x = torch.rand(5,3)
print(x,'\n')
# get the first column and all the rows
print(x[:,0])

tensor([[0.8279, 0.5435, 0.8169],
        [0.6656, 0.3352, 0.1330],
        [0.2213, 0.2218, 0.3831],
        [0.8920, 0.6580, 0.7069],
        [0.9872, 0.7718, 0.7246]]) 

tensor([0.8279, 0.6656, 0.2213, 0.8920, 0.9872])


In [14]:
print(x,'\n')
# get row number 1 and all columns
print(x[1,:])

tensor([[0.8279, 0.5435, 0.8169],
        [0.6656, 0.3352, 0.1330],
        [0.2213, 0.2218, 0.3831],
        [0.8920, 0.6580, 0.7069],
        [0.9872, 0.7718, 0.7246]]) 

tensor([0.6656, 0.3352, 0.1330])


In [15]:
print(x,'\n')
print(x[1,1],'\n')
# item function return the value of tensor
print(x[1,1].item())

tensor([[0.8279, 0.5435, 0.8169],
        [0.6656, 0.3352, 0.1330],
        [0.2213, 0.2218, 0.3831],
        [0.8920, 0.6580, 0.7069],
        [0.9872, 0.7718, 0.7246]]) 

tensor(0.3352) 

0.33522260189056396


In [16]:
x = torch.rand(4,4)
print(x,'\n')
# reshape tensor x from 4*4 to 1*16
y = x.view(16)
print(y)

tensor([[0.8324, 0.4503, 0.1188, 0.0524],
        [0.4662, 0.0931, 0.8720, 0.6721],
        [0.5280, 0.8998, 0.9923, 0.8186],
        [0.5193, 0.0027, 0.6207, 0.3575]]) 

tensor([0.8324, 0.4503, 0.1188, 0.0524, 0.4662, 0.0931, 0.8720, 0.6721, 0.5280,
        0.8998, 0.9923, 0.8186, 0.5193, 0.0027, 0.6207, 0.3575])


In [17]:
print(x,'\n')
# if we put -1 pyTorch will detemine the right dimesion for it
y = x.view(-1,4)
print(y.size())

tensor([[0.8324, 0.4503, 0.1188, 0.0524],
        [0.4662, 0.0931, 0.8720, 0.6721],
        [0.5280, 0.8998, 0.9923, 0.8186],
        [0.5193, 0.0027, 0.6207, 0.3575]]) 

torch.Size([4, 4])


## Numpy and Torch

In [18]:
import numpy as np

In [19]:
a = torch.ones(5)

In [20]:
b = a.numpy()
print(type(b))


<class 'numpy.ndarray'>


In [21]:
# both point to the same memory location, if we make an operation to one, will affect the second 
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [23]:
b = torch.from_numpy(a)

print(type(b))

<class 'torch.Tensor'>


In [27]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  # create tensor in gpu
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  # move tensor to gpu
  y = y.to(device)
  z= x + y


you can't convert gpu tensor to numpy , you should return it back to cpu

In [31]:
z = z.to("cpu")
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)