<a href="https://colab.research.google.com/github/ahmedbasemdev/PyTorch-Tutorial/blob/main/02_Gradient_Calculation_With_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

let's say later we want to calculate the gradient of some function with respect to x then what we have to do is we must specify the argument **requires_grad=True**

In [2]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-2.0642,  1.2816,  0.2339], requires_grad=True)


In [3]:
y = x +2
print(y)

tensor([-0.0642,  3.2816,  2.2339], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
z = z.mean()
print(z)

tensor(10.5089, grad_fn=<MeanBackward0>)


In [5]:
# calculate the gradient"differentiation" of z respect to x
z.backward()
print(x.grad)

tensor([-0.0856,  4.3755,  2.9785])


In [6]:
# prevent x from trakking the gradient
x.requires_grad_(False)
# or
y = x.detach()
# or
with torch.no_grad():
  y = x + 2 
  print


### !!! We need to be careful during optimization !!!
because backward() accumulates the gradient for this tensor into .grad attribute.
Use .zero_() to empty the gradients before a new optimization step!


In [7]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [17]:
x = torch.ones(1,requires_grad=True)
print(x)

tensor([1.], requires_grad=True)


In [18]:
y = x**2
print(y)

tensor([1.], grad_fn=<PowBackward0>)


In [19]:
y.backward()
# compute the differentiation of y respect to x , y = x**2 then dy/dx = 2x , x = 1 then dy/dx = 2 to get this value x.grad

In [20]:
print(x.grad)

tensor([2.])


In [22]:
z = x ** 3
print(z)

tensor([1.], grad_fn=<PowBackward0>)


In [24]:
z.backward()

we get 5 because the grad of x is accumlative 

In [25]:
print(x.grad)

tensor([5.])
