<a href="https://colab.research.google.com/github/ahmedbasemdev/PyTorch-Tutorial/blob/main/02_Gradient_Calculation_With_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch

let's say later we want to calculate the gradient of some function with respect to x then what we have to do is we must specify the argument **requires_grad=True**

In [12]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-0.7448, -0.2746, -0.8267], requires_grad=True)


In [13]:
y = x +2
print(y)

tensor([1.2552, 1.7254, 1.1733], grad_fn=<AddBackward0>)


In [14]:
z = y*y*2
z = z.mean()
print(z)

tensor(3.9527, grad_fn=<MeanBackward0>)


In [15]:
# calculate the gradient of z respect to x
z.backward()
print(x.grad)

tensor([1.6736, 2.3005, 1.5645])


In [17]:
# prevent x from trakking the gradient
x.requires_grad_(False)
# or
y = x.detach()
# or
with torch.no_grad():
  y = x + 2 
  print


### !!! We need to be careful during optimization !!!
because backward() accumulates the gradient for this tensor into .grad attribute.
Use .zero_() to empty the gradients before a new optimization step!


In [21]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
