<a href="https://colab.research.google.com/github/ahmedbasemdev/PyTorch-Tutorial/blob/main/10_Softmax_and_Cross_Entropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
  return np.exp(x) / np.sum(np.exp(x),axis = 0)

In [3]:
x = np.array([2,1,0.1])

In [4]:
outputs = softmax(x)

In [5]:
print(outputs)

[0.65900114 0.24243297 0.09856589]


In [6]:
x = torch.tensor([2,1,.1])
outputs= torch.softmax(x,axis = 0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


## Cross Entropy

In [7]:
def crossEntropy(actual , predicted):
  loss = -np.sum(actual * np.log(predicted)) 
  return loss

In [8]:
Y = np.array([1, 0, 0])
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = crossEntropy(Y, Y_pred_good)
l2 = crossEntropy(Y, Y_pred_bad)
print(f'Loss1 numpy Good: {l1:.4f}')
print(f'Loss2 numpy Bad: {l2:.4f}')


Loss1 numpy Good: 0.3567
Loss2 numpy Bad: 2.3026


## Torch

In [9]:
# we must not emplement the softmax layer
loss = nn.CrossEntropyLoss()

In [10]:
Y = torch.tensor([0])
Y

tensor([0])

In [11]:
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(f'PyTorch Loss1: {l1.item():.4f}')
print(f'PyTorch Loss2: {l2.item():.4f}')


PyTorch Loss1: 0.4170
PyTorch Loss2: 1.8406


# Neural Network

In [13]:
class NeuralNet(nn.Module):

  def __init__(self,inputSize , hiddenState , numClasses):
    super(NeuralNet,self).__init__()

    self.linear1 = nn.Linear(inputSize,hiddenState)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hiddenState,numClasses)
  def forward(self,x):
    net = self.linear1(x)
    net = self.relu(net)
    net = self.linear2(net)
    # no softmax at the end
    return net

In [14]:
model = NeuralNet(28*28 , 5 , 3)

criterion = nn.CrossEntropyLoss() # applies softmax

In [15]:
# in previous network we implement mutpliclass prediction to compute the loss we must not add softmax layer at the end
# if we implement binary class prediction we can use Binary cross entropy and we must apply softmax at the end